version: '3'
services:
  influxdb:
    env_file:
      - .env
    image: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./monitoring/influxdb:/var/lib/influxdb
  grafana:
    env_file:
      - .env
    image: grafana/grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    ports:
      - "3333:3333"